######################################################################
# Automatically generated by qmake (2.01a) sam. mai 31 15:38:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += path2checksum.cpp
